USE LC_KANDY;

INSERT INTO member 
(
    email, 
    passphrase,
    fullName,
    preferredName,
    frontOfficeId,
    departmentId,
    backOfficeId,
    joinedDate,
    roleId,
    contactNo,
    aiesecEmail,
    gender,
    nic,
    birthDate,
    facebookLink,
    linkedinLink,
    instagramLink,
    registerNo,
    schoolName,
    homeAddress,
    homeContact,
    districtId,
    photoLink,
    boardingAddress
)
VALUES 
(
    "astromp01@gmail.com", 
    123,
    "John Doe",
    "John",
    "LCP",
    "LCP",
    NULL,
    "2019-01-01",
    "LCP",
    "1234567890",
    "john@example.com",
    "M",
    "1234567890",
    "2002-01-01",
    "john@facebook.com",
    "john@linkedin.com",
    "john@instagram.com",
    "E/02/002",
    "School",
    "No.2 Kings Street, Kandy",
    "1234567890",
    "1",
    "https://drive.google.com/file/d/1ADL_F1F12M-f9DwB416OzOysLWP-BigE/view?usp=sharing",
    "No.3 Kings Street, Kandy"
)
,(
    'sankapeeris360@gmail.com',
    '123',
    'Jane Smith', 
    'Janie', 
    "oGV", 
    "CXP", 
    NULL, 
    '2022-08-20', 
    "SPL", 
    '555-123-4567', 
    'jane.smith@aiesec.org', 
    'F', 
    "9876543210", 
    '1998-03-25', 
    'https://www.facebook.com/janesmith', 
    'https://www.linkedin.com/in/janesmith', 
    'https://www.instagram.com/janesmith', 
    '2', 
    'Sample High School', 
    '789 Oak Ave, Town', 
    '123-987-4560', 
    4, 
    'https://drive.google.com/file/d/1bfWwEMlz2OZT35i7GPinWkjSuhgqvu7z/view?usp=sharing', 
    '567 Pine Ave, Town'
)
,(
    'michael.johnson@example.com', 
    'mikepass', 
    'Michael Johnson', 
    'Mike', 
    "oGV", 
    "CXP", 
    NULL, 
    '2021-05-03', 
    "SPL", 
    '999-555-1212', 
    'michael.johnson@aiesec.org', 
    'M', 
    "5555555550", 
    '1990-12-15', 
    'https://www.facebook.com/mikejohnson', 
    'https://www.linkedin.com/in/mikejohnson', 
    'https://www.instagram.com/mikejohnson', 
    '3', 
    'Test High School', 
    '111 Maple Rd, Village', 
    '777-888-9999', 
    1, 
    'https://drive.google.com/file/d/12eQiW6RUUVqPkY37vxYM1KXGSPTT11MD/view?usp=sharing', 
    '222 Birch Rd, Village'
)
,(
    'alexandra.jackson@example.com', 
    'alexpass', 
    'Alexandra Jackson', 
    'Alex', 
    "oGV", 
    "CXP", 
    NULL,
    '2020-11-28', 
    "TM", 
    '111-222-3333', 
    'alexandra.jackson@aiesec.org', 
    'M', 
    "4444444440", 
    '1988-07-20', 
    'https://www.facebook.com/alexjackson', 
    'https://www.linkedin.com/in/alexjackson', 
    'https://www.instagram.com/alexjackson', 
    '4', 
    'Example Academy', 
    '555 Elm Ave, Village', 
    '333-111-2222', 
    2, 
    'https://drive.google.com/file/d/1N4QLzpMHWTY2vXxzYWI126NeRy3RHE3Z/view?usp=sharing', 
    '666 Maple Ave, Village'
),
(
    "tomioka@example.com", 
    123,
    "mizu123",
    "Giyuu",
    "oGV", 
    "CXP", 
    NULL,
    "2019-01-01",
    "TL",
    "1234567890",
    "tomioka@example.com",
    "M",
    "1234567890",
    "2002-01-01",
    "tomioka@facebook.com",
    "tomioka@linkedin.com",
    "tomioka@instagram.com",
    "E/02/003",
    "School",
    "No.2 Kings Street, Kandy",
    "1234567890",
    "1",
    "https://drive.google.com/file/d/1_5ttCoLPOlmsMD5lIk8wZ11fxj_lBTgR/view?usp=sharing",
    "No.3 Kings Street, Kandy"
);
